### ISSUE TITLE
REPL does not eval-print-loop

### ISSUE THREAD

**Issue by gamecubate** [jraines/repl-lite#1]
Does this work? If it does, instructions would be good. All I managed to do in Atom was to toggle what looks like an unresponsive (no eval-print-loop) REPL.

**Comment by haywoood** [comment]
yea it works, just not with `enter` or `shift-enter`. you have to use the eval sexp or selection commands. `ctrl-r (let go) i` or `ctrl-r (let go) j`

**Comment by gamecubate** [comment]
@lsdafjklsd Thanks for the tips. Tried but REPL remains unresponsive (atom 1.12.7). As full-time front-end CLJS programmer, would love for this to work. Will dig a bit more and fallback on proto-repl if all else fails. @jraines seems absent so I will close this in a few days.

**Comment by jraines** [comment]
just now seeing this, sorry.  I'll take a look within a few days, maybe this weekend

**Comment by gamecubate** [comment]
Thanks. Yes. But I may or may not end up using this anyway. I am very much into CLJS (for daily paid work at local paper) and use atom for most of my coding, but have been considering switching to emacs+cider for a while. So please don't spend valuable time on this just for this one issue. **But will be glad to test and provide feedback after your fix.**

**Comment by jraines** [comment]
I just upgraded my Atom to 1.12.7 and it still works for me.  Steps:

1. Hit `ctrl-r r`
2. Type in your nREPL port number in the popup (drives me nuts that you can't copy/paste into it)
3. You should see a connection message and a prompt
4. Type out an expression and hit `ctrl-r i` or `ctrl-r j`  (must be inside or on the parens of the block or sexp you want to eval

If you're using a vim plugin, you must be in normal mode, not insert mode.

Hope this helps.

**Comment by gamecubate** [comment]
I will test this in the next few days and will leave feedback right after. Thanks for the update.

**Comment by gamecubate** [comment]
... a few days ... HA!

Tested on my side, at last. Works. Thanks! Closing issue.
